import { BaseLayoutedDiagram, Element } from "@hylimo/diagram-common";
import { DynamicLanguageServerConfig, Edit, IncrementalUpdate } from "@hylimo/diagram-protocol";

/**
 * Handles transactional edits to a TextDocument
 *
 * @param E the type of edit handled
 */
export interface EditHandler<E extends Edit> {
    /**
     * The type of the action
     */
    type: NonNullable<E["types"]>[0];

    /**
     * Predicts the action diff based on the layouted diagram and the last applied action
     *
     * @param layoutedDiagram the layouted diagram
     * @param lastApplied the last applied values
     * @param newest the newest values
     * @param elements the elements to apply the prediction to
     * @returns the incremental updates generated by the prediction
     */
    predictActionDiff(
        layoutedDiagram: BaseLayoutedDiagram,
        lastApplied: E["values"] | undefined,
        newest: E["values"],
        elements: Element[]
    ): IncrementalUpdate[];

    /**
     * Transforms the action based on settings and other values
     *
     * @param edit the action to transform
     * @param config the language server config
     */
    transformEdit(edit: E, config: DynamicLanguageServerConfig): void;
}
