<template>
    <div class="diagram-chooser" ref="diagramChooser">
        <input
            v-model="inputFilenameOrPlaceholder"
            ref="diagramSelect"
            class="diagram-select"
            :class="{ untitled: !showDialog && !inputFilename }"
            :placeholder="diagramSource != undefined ? 'Search or create diagram' : undefined"
            :readonly="readonly"
            :title="diagramSource?.canSave?.value ? 'Unsaved changes' : undefined"
            @focus="
                if (!readonly) {
                    ($event.target as HTMLInputElement).select();
                }
                openDialog();
            "
            @click="openDialog"
            @input="openDialog"
        />
        <span
            class="select-icon"
            :class="{
                'vpi-file-stack-light': diagramSource?.type === 'browser',
                'vpi-file-check-light': diagramSource?.type === 'file' && !diagramSource?.canSave?.value,
                'vpi-file-warning-light': diagramSource?.type === 'file' && diagramSource?.canSave?.value,
                'vpi-cloud-check-light': diagramSource?.type === 'embedded' && !diagramSource?.canSave?.value,
                'vpi-cloud-warning-light': diagramSource?.type === 'embedded' && diagramSource?.canSave?.value
            }"
        />
        <Transition name="dialog">
            <div v-show="showDialog && diagramEntries.length > 0" class="dialog-anchor">
                <ScrollArea ref="scrollArea" class="dialog" @mousemove="onMouseMove">
                    <div
                        v-for="(diagram, index) in diagramEntries"
                        :key="diagram.filename"
                        class="item"
                        :class="{
                            selected: index === selectedIndex,
                            current:
                                diagram.filename === diagramSource?.filename && diagram.type === diagramSource?.type
                        }"
                        :data-index="index"
                        @mouseenter="!disableMouseOver && (selectedIndex = index)"
                        @focusin="selectedIndex = index"
                        @click="selectDiagram(diagram)"
                    >
                        <template v-if="diagram.type === 'new'">
                            <span class="filename"
                                >Create new:
                                <span class="available-diagram-filename">{{ diagram.filename }}</span></span
                            >
                            <div class="icon">
                                <span class="vpi-plus" />
                            </div>
                        </template>
                        <template v-else-if="diagram.type === 'file'">
                            <span class="filename">{{ diagram.filename }}</span>
                            <div class="icon">
                                <span class="vpi-file" />
                            </div>
                        </template>
                        <template v-else-if="diagram.type === 'open-file'">
                            <span class="filename">Open file...</span>
                            <div class="icon">
                                <span class="vpi-folder-open" />
                            </div>
                        </template>
                        <template v-else>
                            <span class="filename">{{ diagram.filename }}</span>
                            <span class="info">
                                last edited
                                <relative-time :datetime="diagram.lastChange" />
                            </span>
                            <button class="delete-button icon" @click.stop="deleteDiagram(diagram)">
                                <span class="vpi-trashcan" />
                            </button>
                        </template>
                    </div>
                </ScrollArea>
            </div>
        </Transition>
        <!-- the preview svg is generated by the diagram renderer, and thus safe to inject -->
        <Transition name="dialog">
            <div
                v-if="showDialog && previewSvg != undefined"
                ref="previewElement"
                class="preview"
                :style="{ top: `${previewTop}px`, '--preview-max-width': `${previewMaxWidth}px` }"
                v-html="previewSvg"
            />
        </Transition>
    </div>
</template>
<script setup lang="ts">
import { computed, inject, markRaw, nextTick, ref, watch, type PropType } from "vue";
import {
    onClickOutside,
    onKeyStroke,
    useEventListener,
    useResizeObserver,
    useWindowSize,
    watchDebounced,
    watchImmediate
} from "@vueuse/core";
import { useData } from "vitepress";
import "@github/relative-time-element";
import MiniSearch, { type SearchResult } from "minisearch";
import type { DiagramMetadata } from "../util/diagramStorageSource";
import type { DiagramSource } from "../util/diagramSource";
import { useDiagramPreviewProvider } from "../util/diagramPreview";
import { languageServerConfigKey } from "../theme/injectionKeys";
import ScrollArea from "./ScrollArea.vue";

interface DiagramEntry extends DiagramMetadata {
    type: "file" | "open-file" | "new" | "browser";
}

const props = defineProps({
    diagramSource: {
        type: Object as PropType<DiagramSource>,
        required: false
    },
    allDiagrams: {
        type: Array as PropType<DiagramMetadata[]>,
        required: true
    },
    readonly: {
        type: Boolean,
        required: true
    },
    loadDiagram: {
        type: Function as PropType<(filename: string) => Promise<string | undefined>>,
        required: true
    }
});

/**
 * Time to wait before rendering the preview of the selected diagram.
 * Prevents rendering previews of all diagrams the mouse passes over.
 */
const previewDebounce = 150;

/**
 * Minimal distance the preview keeps from the edges of the viewport.
 */
const previewViewportMargin = 16;

/**
 * Horizontal gap between the dialog and the preview.
 */
const previewGap = 12;

/**
 * Maximum width of the preview.
 */
const previewMaxSize = 400;

/**
 * Width the preview needs at least, previews are not rendered at all if less space is available.
 */
const previewMinSize = 180;

const emit = defineEmits<{
    openDiagram: [value: string];
    openFile: [];
    deleteDiagram: [value: string];
    createDiagram: [value: string];
}>();

const inputFilename = ref("");

watchImmediate(
    () => props.diagramSource,
    (source) => {
        inputFilename.value = source?.filename ?? "";
    }
);

const showDialog = ref(false);
const disableMouseOver = ref(true);
const didInputChange = ref(false);
const selectedIndex = ref(-1);
const diagramChooser = ref<HTMLElement | null>(null);
const diagramSelect = ref<HTMLInputElement | null>(null);
const diagramEntries = ref<DiagramEntry[]>([]);

const inputFilenameOrPlaceholder = computed({
    get: () => {
        if (props.diagramSource == undefined) {
            return "";
        } else if (showDialog.value) {
            return inputFilename.value;
        } else {
            return inputFilename.value || "Untitled diagram";
        }
    },
    set: (value) => {
        openDialog();
        didInputChange.value = true;
        inputFilename.value = value;
    }
});

const searchIndex = computed(() => {
    const index = new MiniSearch<DiagramEntry>({
        fields: ["filename"],
        storeFields: ["filename", "lastChange", "type"],
        idField: "filename",
        searchOptions: {
            prefix: true,
            fuzzy: 0.2
        }
    });
    index.addAll(props.allDiagrams.map((diagram) => ({ ...diagram, type: "browser" }) as const));
    if (props.diagramSource?.type === "file") {
        index.add({
            filename: props.diagramSource.filename,
            lastChange: new Date().toISOString(),
            type: "file"
        });
    }
    return markRaw(index);
});

function computDefaultDiagramEntries(): DiagramEntry[] {
    const entries: DiagramEntry[] = [...props.allDiagrams.map((diagram) => ({ ...diagram, type: "browser" }) as const)];
    if (props.diagramSource?.type === "file") {
        entries.unshift({
            filename: props.diagramSource.filename,
            lastChange: new Date().toISOString(),
            type: "file"
        });
    }
    if ("showOpenFilePicker" in window) {
        entries.unshift({ filename: "", type: "open-file", lastChange: new Date().toISOString() });
    }
    return entries;
}

function updateDiagramEntries(): void {
    const name = inputFilename.value;
    if (name.length === 0 || !didInputChange.value) {
        diagramEntries.value = computDefaultDiagramEntries();
        return;
    }
    const searchResults = searchIndex.value.search(name) as (DiagramEntry & SearchResult)[];
    const newResults: DiagramEntry[] = [];
    if (props.allDiagrams.every((d) => d.filename !== name)) {
        newResults.push({ filename: name, type: "new", lastChange: new Date().toISOString() });
    }
    newResults.push(...searchResults);
    diagramEntries.value = newResults;
}

watch([inputFilename, () => props.allDiagrams], () => {
    if (showDialog.value) {
        updateDiagramEntries();
    }
});

function openDialog(): void {
    if (showDialog.value || props.readonly) {
        return;
    }
    updateDiagramEntries();
    showDialog.value = true;
}

function closeDialog(): void {
    showDialog.value = false;
    diagramSelect?.value?.blur();
    inputFilename.value = props.diagramSource?.filename ?? "";
    didInputChange.value = false;
}

function selectDiagram(diagram: DiagramEntry): void {
    if (diagram.type === "file") {
        closeDialog();
        return;
    }
    if (props.diagramSource?.canSave?.value) {
        const confirmed = window.confirm(`Discard changes to '${props.diagramSource.filename}'?`);
        if (!confirmed) {
            closeDialog();
            return;
        }
    }
    if (diagram.type === "new") {
        emit("createDiagram", diagram.filename);
    } else if (diagram.type === "open-file") {
        emit("openFile");
    } else if (diagram.type === "browser") {
        emit("openDiagram", diagram.filename);
    }
    closeDialog();
}

function deleteDiagram(diagram: DiagramEntry): void {
    const confirmed = window.confirm(`Are you sure you want to delete diagram '${diagram.filename}'?`);
    if (confirmed) {
        emit("deleteDiagram", diagram.filename);
    }
}

onClickOutside(diagramChooser, () => {
    closeDialog();
});

watch(diagramEntries, (r) => {
    selectedIndex.value = r.length ? 0 : -1;
    scrollToSelectedResult();
});

function scrollToSelectedResult() {
    nextTick(() => {
        const selectedEl = diagramChooser.value?.querySelector(".item.selected");
        selectedEl?.scrollIntoView({ block: "nearest" });
    });
}

const languageServerConfig = inject(languageServerConfigKey)!;
const { isDark } = useData();
const { width: windowWidth } = useWindowSize();
const previewProvider = useDiagramPreviewProvider();
const scrollArea = ref<InstanceType<typeof ScrollArea> | null>(null);
const previewElement = ref<HTMLElement | null>(null);
const previewSvg = ref<string>();
const previewTop = ref(0);
const previewMaxWidth = ref(0);
let previewRequestId = 0;

const diagramBackground = computed(() => {
    const config = languageServerConfig.diagramConfig.value;
    return isDark.value ? config.darkBackgroundColor : config.lightBackgroundColor;
});

const selectedEntry = computed(() => (showDialog.value ? diagramEntries.value[selectedIndex.value] : undefined));
const previewFits = computed(() => previewMaxWidth.value >= previewMinSize);

watch(selectedEntry, () => {
    previewRequestId++;
    previewSvg.value = undefined;
});
watchDebounced([selectedEntry, previewFits, previewProvider.revision], updatePreview, { debounce: previewDebounce });
watch([windowWidth, showDialog], () => nextTick(updatePreviewMaxWidth), { immediate: true });
watch(previewSvg, () => nextTick(updatePreviewPosition));
useResizeObserver(previewElement, updatePreviewPosition);
useEventListener(
    () => scrollArea.value?.viewport,
    "scroll",
    () => updatePreviewPosition()
);

/**
 * Updates the width available to the preview next to the dialog.
 * Only meaningful while the dialog is shown, as it has no size otherwise.
 */
function updatePreviewMaxWidth(): void {
    const dialog = diagramChooser.value?.querySelector(".dialog");
    if (!showDialog.value || dialog == undefined) {
        return;
    }
    const available = window.innerWidth - dialog.getBoundingClientRect().right - previewGap - previewViewportMargin;
    previewMaxWidth.value = Math.min(previewMaxSize, Math.max(0, available));
}

/**
 * Returns the source of the diagram associated with the provided entry, if it has one.
 *
 * @param entry the entry to get the source of
 * @returns the source of the diagram, or undefined if the entry does not represent an existing diagram
 */
async function getDiagramCode(entry: DiagramEntry | undefined): Promise<string | undefined> {
    if (entry?.type === "browser") {
        return props.loadDiagram(entry.filename);
    } else if (entry?.type === "file") {
        return props.diagramSource?.code.value;
    } else {
        return undefined;
    }
}

/**
 * Renders the preview of the currently selected entry.
 * Outdated results are discarded, as previews are rendered one after another.
 */
async function updatePreview(): Promise<void> {
    const requestId = ++previewRequestId;
    const code = previewFits.value ? await getDiagramCode(selectedEntry.value) : undefined;
    const preview = code != undefined ? await previewProvider.getPreview(code) : undefined;
    if (requestId === previewRequestId) {
        previewSvg.value = preview;
    }
}

/**
 * Vertically aligns the preview with the selected entry, while keeping it inside the dialog and the viewport.
 */
function updatePreviewPosition(): void {
    const chooser = diagramChooser.value;
    const preview = previewElement.value;
    const item = chooser?.querySelector(".item.selected");
    const dialog = chooser?.querySelector(".dialog");
    if (chooser == undefined || preview == undefined || item == undefined || dialog == undefined) {
        return;
    }
    const chooserTop = chooser.getBoundingClientRect().top;
    const dialogRect = dialog.getBoundingClientRect();
    const bottom = Math.min(dialogRect.bottom, window.innerHeight - previewViewportMargin);
    const minTop = dialogRect.top - chooserTop;
    const maxTop = bottom - preview.offsetHeight - chooserTop;
    previewTop.value = Math.max(minTop, Math.min(item.getBoundingClientRect().top - chooserTop, maxTop));
}

onKeyStroke("ArrowUp", (event) => {
    if (!showDialog.value) {
        return;
    }
    event.preventDefault();
    selectedIndex.value--;
    if (selectedIndex.value < 0) {
        selectedIndex.value = diagramEntries.value.length - 1;
    }
    disableMouseOver.value = true;
    scrollToSelectedResult();
});

onKeyStroke("ArrowDown", (event) => {
    if (!showDialog.value) {
        return;
    }
    event.preventDefault();
    selectedIndex.value++;
    if (selectedIndex.value >= diagramEntries.value.length) {
        selectedIndex.value = 0;
    }
    disableMouseOver.value = true;
    scrollToSelectedResult();
});

onKeyStroke("Enter", (e) => {
    if (!showDialog.value || e.isComposing || (e.target instanceof HTMLButtonElement && e.target.type !== "submit")) {
        return;
    }

    const selectedDiagram = diagramEntries.value[selectedIndex.value];
    if (e.target instanceof HTMLInputElement && !selectedDiagram) {
        e.preventDefault();
        return;
    }

    if (selectedDiagram != undefined) {
        selectDiagram(selectedDiagram);
    }
});

onKeyStroke("Escape", () => {
    closeDialog();
});

function onMouseMove(e: MouseEvent) {
    if (!disableMouseOver.value || !showDialog.value) {
        return;
    }
    const el = (e.target as HTMLElement)?.closest<HTMLAnchorElement>(".item");
    const index = Number.parseInt(el?.dataset.index!);
    if (index >= 0 && index !== selectedIndex.value) {
        selectedIndex.value = index;
    }
    disableMouseOver.value = false;
}
</script>
<style scoped>
.diagram-chooser {
    --dialog-width: min(75vw, 500px);

    margin-left: 10px;
    position: relative;
    flex: 0 1 30ch;
}

/*
 * From here on there is a realistic chance of fitting a preview next to the list,
 * so the list gives up some of its width. Whether a preview is actually shown is decided
 * by the component based on the space that is really left next to the dialog.
 */
@media (min-width: 700px) {
    .diagram-chooser {
        --dialog-width: min(45vw, 500px);
    }
}

@media (max-width: 500px) {
    .diagram-chooser:not(.screen-menu) {
        display: none;
    }
}

.diagram-select {
    border-radius: 6px;
    padding: 2px 12px 2px 28px;
    height: 40px;
    width: 100%;
    flex-shrink: 1;
    box-sizing: border-box;
    background-color: var(--vp-c-bg-alt);
    border: 1px solid transparent;
    font-size: 13px;
    font-family: var(--vp-font-family-base);
    font-weight: 500;
}

.diagram-select:hover:not(:disabled),
.diagram-select:focus:not(:disabled) {
    border-color: var(--vp-c-brand-1);
}

.diagram-select.untitled {
    font-style: italic;
}

.select-icon {
    position: absolute;
    left: 4px;
    top: 0;
    bottom: 0;
    margin: auto;
    width: 20px;
    height: 20px;
    pointer-events: none;
    color: var(--vp-c-text-2);
}

.select-icon.vpi-file-light {
    width: 16px;
    height: 16px;
}

.available-diagram-filename {
    font-style: italic;
}

/*
 * The dialog is positioned by a wrapper, as reka-ui sets position: relative on the scroll area
 * root as an inline style, which cannot be overwritten by a class.
 */
.dialog-anchor {
    position: absolute;
    top: calc(var(--vp-nav-height) - 6px);
    left: 0;
    width: var(--dialog-width);
    transition:
        opacity 0.25s,
        visibility 0.25s;
    opacity: 1;
}

.dialog {
    border-radius: 12px;
    padding: 12px;
    border: 1px solid var(--vp-c-divider);
    background-color: var(--vp-c-bg-elv);
    box-shadow: var(--vp-shadow-3);
    width: 100%;
    max-height: calc(80vh - var(--vp-nav-height));
    box-sizing: border-box;
}

.dialog-enter-from,
.dialog-leave-to {
    opacity: 0;
}

.preview {
    /* --preview-max-width is provided by the component, based on the space left next to the dialog */
    --preview-max-height: min(400px, 50vh);

    position: absolute;
    left: calc(var(--dialog-width) + 12px);
    transition:
        opacity 0.25s,
        visibility 0.25s;
    opacity: 1;
    display: flex;
    padding: 12px;
    border-radius: 12px;
    border: 1px solid var(--vp-c-divider);
    background-color: v-bind(diagramBackground);
    box-shadow: var(--vp-shadow-3);
    box-sizing: border-box;
    pointer-events: none;
}

/* the limits are applied to the svg itself, as percentages do not work in a container sized by its content */
.preview :deep(svg) {
    width: auto;
    height: auto;
    max-width: var(--preview-max-width);
    max-height: var(--preview-max-height);
}

.item {
    font-size: 14px;
    padding-left: 12px;
    border-radius: 6px;
    cursor: pointer;
    border: 2px solid transparent;
    display: flex;
    align-items: center;
    box-sizing: border-box;
}

.filename {
    font-weight: 500;
    flex: 1 1 0;
    margin-right: 36px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}

.info {
    font-size: 12px;
    color: var(--vp-c-text-2);
}

.item.current {
    background-color: var(--vp-c-default-soft);

    .filename {
        color: var(--vp-c-brand-1);
    }
}

.item.selected {
    border-color: var(--vp-c-brand-1);
}

.icon {
    height: 36px;
    width: 36px;
    display: flex;
    justify-content: center;
    align-items: center;
    color: var(--vp-c-text-1);

    span {
        width: 16px;
        height: 16px;
    }
}

.delete-button:hover {
    color: var(--vp-c-danger-1);
    transition: color 0.25s;
}
</style>
