name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build packages
        run: npm run build
      - name: Build website
        run: npm run build
        working-directory: website
      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./website/build
          force_orphan: true
          external_repository: hylimo/hylimo.github.io
          publish_branch: main