name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    deploy:
        name: Deploy to GitHub Pages
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: npm
            - name: Install dependencies
              run: npm ci
            - name: Build packages
              run: npm run build
            - name: Build website
              run: npm run build
              working-directory: website
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              if: ${{ github.event_name != 'pull_request' }}
              with:
                  deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  publish_dir: ./website/.vitepress/dist
                  force_orphan: true
                  external_repository: hylimo/hylimo.github.io
                  publish_branch: main
