name: Release Packages

on:
  release:
    types: [published]

permissions:
  id-token: write

jobs:
  deploy:
    name: Release Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: npm
          registry-url: "https://registry.npmjs.org"
      - name: Update npm
        run: npm install -g npm@latest
      - name: Install dependencies
        run: npm ci
      - name: Build packages
        run: npm run build
      - name: Publish packages
        run: npm publish --provenance --access public --workspaces
